stages:
  - compile
  - deploy

compile:
  stage: compile
  image: rust:latest
  before_script:
    - apt-get -qq update && apt-get -qq install texlive-fonts-extra
  script:
    - pdflatex cv.tex
  artifacts:
    paths:
      - cv.pdf

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
  script:
    - aws s3 cp cv.pdf s3://$BUCKET_NAME --acl public-read
